version: 2

sources:
  - name: raw        # dbt'de kullanacağın kısa (takma) isim
    schema: dbt_dkoroglu   # BigQuery'deki gerçek dataset adı
    tables:
      - name: sales       # dbt'de göreceğin kısa tablo ismi
        identifier: raw_gz_sales   # BigQuery'deki gerçek tablo adı
      - name: product
        identifier: raw_gz_product
      - name: ship
        identifier: raw_gz_ship

